### ISSUE TITLE
Transformation error (This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (4:2))

### ISSUE THREAD

**Issue by shofmannka** [ember-codemods/ember-data-codemod#117]
I have created a new project with ember version 3.22 and then created a new model with one string member. If i then try to perform the ember-data-codemod on this model i get the error 
Transformation error (This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (4:2))

**Comment by dcyriller** [comment]
Thanks for reporting!

I tried to reproduce with no luck. 🤔 Could you help me understand by telling me which ember-data and ember-data-codmod versions you use?

I generated a new app and then ran `yarn ember g model bike`. In a newly generated app, the latest syntaxes are generated - without the need to run this codemod. But I modified the imports to the old syntax and the codemod ran properly.

**Comment by shofmannka** [comment]
@dcyriller I am using the latest ember version 3.24 and the latest codemod version. If i generate a new model i get e.g 
import Model, { attr } from '@ember-data/model';

export default class Test2Model extends Model {
  @attr('string') par1;
  @attr('number') par2;
}
If i then run the codemod i receive the described error. If i use the example from the transform description then there is no error.

**Comment by dcyriller** [comment]
Thanks for the details. I'll try to have a look when I have an available cycle.

Luckily, if you are in new a app and if you use ember-data > v3.14.0-alpha.2, you don't need to run this codemod (provided you generate the resources with `ember generate`).

**Comment by dcyriller** [comment]
Fix in #118
