### ISSUE TITLE
Awaiting upstream PR - fix for jscodeshift when path is undefined

### ISSUE THREAD

**Issue by snewcomer** [ember-codemods/ember-data-codemod#20]
https://github.com/facebook/jscodeshift/pull/334

```
(node:84942) UnhandledPromiseRejectionWarning: TypeError: array is not iterable
```

**Comment by snewcomer** [comment]
One option is we can use `fs.lstatSync` on our side to filter out those paths that don't exist in the user's project.  What do you think?

**Comment by dcyriller** [comment]
It’s a good idea!

**Comment by snewcomer** [comment]
Anybody that is coming across this - you can hop into [here](https://github.com/ember-codemods/ember-data-codemod/blob/master/bin/ember-data-codemod.js#L14) and update this array to just `app` if you are running this on your project.

**Comment by dcyriller** [comment]
You can also pass `app` as an arg: `npx github:ember-codemods/ember-data-codemod app`, it will bypass the array / work around the bug.

**Comment by dcyriller** [comment]
Here, we have switched to using codemod-cli: https://github.com/ember-codemods/ember-data-codemod/pull/30

Switching to codemod-cli, we've made passing a path to the codemod _required_. So the path is no longer undefined  and this issue should be gone now.
