### ISSUE TITLE
Migrate to `ember-codemods` org?

### ISSUE THREAD

**Issue by rwjblue** [ember-codemods/ember-data-codemod#4]
I’ve slowly been moving the general community codemods that I’ve made into the ember-codemods GitHub org, and inviting others to join me over in that org. Mostly as a way to:

* increase visibility 
* reduce bus factor
* reduce overall work load (many other codemodders make light work of the overall maintenance)

We’d make sure to preserve the current permissions (e.g. no reduction in control) if we did the transition.

Would this be something y’all would be open to?

**Comment by rwjblue** [comment]
Just in case this is something you'd like to do, I shot you an invite to join the org...

**Comment by dcyriller** [comment]
@rwjblue yes, of course. @runspired also suggested the ember-data organization. But after all `ember-codemods` sounds a good option.

This is pretty much a fork of ember-modules-codemod that I've done without reviews. If you have time to review it a bit, I would appreciate!

I'll fix a bug, update the README and initiate the migration.
