### ISSUE TITLE
Leave RESTAdapter imported from ds-improved-ajax as it is

### ISSUE THREAD

**Issue by tniezurawski** [ember-codemods/ember-data-codemod#42]
`globals-to-ember-data-imports` transform converts imports made for `RESTAdapter` from `ds-improved-ajax/adapters/rest` package into `@ember-data/adapter/rest`.

Git diff, after applying the transform:
```diff
- import RESTAdapter from 'ds-improved-ajax/adapters/rest';
+ import RESTAdapter from '@ember-data/adapter/rest';
```

The transform should leave this line as it is. Because, in this case, it is expected to import `RESTAdapter` from 3rd party addon.

**Comment by dcyriller** [comment]
Thanks for reporting @tniezurawski!

I've submitted a PR to fix that.

**Comment by tniezurawski** [comment]
Thanks for fixing 🙌
