### ISSUE TITLE
Leave { Serializer } imported from ember-cli-mirage as it is

### ISSUE THREAD

**Issue by tniezurawski** [ember-codemods/ember-data-codemod#43]
If you happen to run `globals-to-ember-data-imports` transform on the whole project and you have a serializer for `ember-cli-mirage` like an application serializer for example (`/mirage/serializers/application.js`) then you'll see unwanted change:

```diff
- import { Serializer } from 'ember-cli-mirage';
+ import Serializer from '@ember-data/serializer';
```

The transform should leave this line as it is. Because, in this case, it is expected to import `{ Serializer }` from 3rd party addon.

**Workaround:**
Don't run the transform against the whole project directory. Run in against specific directories.

**Comment by dcyriller** [comment]
It will be fixed by https://github.com/ember-codemods/ember-data-codemod/pull/44 (the third commit adds a test for this snippet).

**Comment by dcyriller** [comment]
Tracking on https://github.com/ember-codemods/ember-data-codemod/issues/42 (one fix both issues)

**Comment by dcyriller** [comment]
Thank you for taking the time to report!

**Comment by tniezurawski** [comment]
Thanks for fixing 🙌
